### ISSUE TITLE
docs action is failing

### ISSUE THREAD

**Issue by martinfleis** [pysal/tobler#213]
https://github.com/pysal/tobler/actions/runs/9519677622/job/26243393334

**Comment by sjsrey** [comment]
Looks like an older version of Sphinx is being used:
```
Running Sphinx v5.3.0
```

whereas [libpysal](https://github.com/pysal/libpysal/actions/runs/9454509191/job/26042204462#step:5:9) (where docs build fine):
```
Running Sphinx v7.3.7
```

**Comment by sjsrey** [comment]
It started failing after [deps added to ci](https://github.com/pysal/tobler/commit/704d7dddfa8f304b6d1bae11aeb0c8f96c3e9128#diff-515324956ca2a236d7ddd9b922b7323ac9a96e0332cce7e9586ee105316fd3b0R32)

Since these are now in the [pyproject.toml](https://github.com/pysal/tobler/blob/d87ed4dd26fad4ef528995a9c2f607d052177e74/pyproject.toml#L51), maybe we can remove them from the ci?

**Comment by knaaptime** [comment]
resolved by #219
