### ISSUE TITLE
Add Pycnophylactic Interpolation

### ISSUE THREAD

**Issue by sjsrey** [pysal/tobler#95]
[Tobler paper](http://www.geog.ucsb.edu/~kclarke/Geography232/Pycno.pdf)

**Comment by danlewis85** [comment]
In case it is helpful, here is some python code I wrote to do pycnophylactic smoothing: https://github.com/danlewis85/pycno

It's based in part on Chris Brunsdon's R package: https://cran.r-project.org/web/packages/pycno/index.html

**Comment by knaaptime** [comment]
awesome, thanks for sharing this! It's a huge help! Any chance you'd be open to contributing that code here? We'll add you as an author and maybe write a wrapper or two for API consistency with the other interpolators?

**Comment by knaaptime** [comment]
hey @danlewis85 I had a chance to play around with [pycno](https://github.com/danlewis85/pycno) and it's great! I wanted to check in again and see if you would be ok contributing some of that code here? We'd love to include it

I wrote a little wrapper for consistency with `tobler` and tweaked one or two of your functions very slightly, though i'd need your permission before integrating it here since `pycno` is GPL but the pysal ecosystem is BSD. Would you be alright with that?

**Comment by danlewis85** [comment]
Hi @knaaptime,

Yes, fully happy for you to use the pycno code for tobler, you have my permission. The GPL license is entirely arbitrary and I have no problem with code moving to the pysal ecosystem.

**Comment by knaaptime** [comment]
you rule. thanks!
